# Generated by Django 5.2.8 on 2025-11-15 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_wears', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Designer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='designer',
            name='brand',
            field=models.CharField(choices=[('Gucci', 'Gucci wears'), ('Vuitton', 'Vuitton wears'), ('Prada', 'Prada wears')], default='Gucci', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='designer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='designer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designer_wears.designer'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
